INSERT INTO TBL_CATEGORY (NAME) VALUES ('Fabricação Própria');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Nacional');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Importado');
INSERT INTO TBL_CATEGORY (NAME) VALUES ('Premium');

INSERT INTO TBL_PRODUCT (NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES ('Computador XP', 'I9,SSD500,HD1T, 32GB', 5999.99,1,true,true);

INSERT INTO TBL_PRODUCT (NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES ('Computador XR', 'I7,SSD500,HD1T, 16GB', 4999.99,2,true,false);

INSERT INTO TBL_PRODUCT (NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES ('Computador XR', 'I7,SSD256,HD1T, 16GB', 4599.99,3,false,false);

INSERT INTO TBL_PRODUCT (NAME,DESCRIPTION,PRICE,CATEGORY_ID,PROMOTION, NEW_PRODUCT)
VALUES ('Computador XR', 'I7,HD1T, 16GB', 4000,4,false,false);