INSERT INTO TBL_CATEGORY (ID,NAME) VALUES (1, 'Fabricação Própria');
INSERT INTO TBL_CATEGORY (ID,NAME) VALUES (2, 'Nacional');
INSERT INTO TBL_CATEGORY (ID,NAME) VALUES (3, 'Importado');
INSERT INTO TBL_CATEGORY (ID,NAME) VALUES (4, 'Premium');